### PR TITLE
Issue 75: Fix bug where last row is Inf

### LINKED ISSUE #75: Fix bug introducing last row as Inf in measles example
**Bug description**
Noticed when running example analysis on measles in https://github.com/epinowcast/baselinenowcast-paper/pull/9 that we are getting a row of Infs for the retrospective nowcasts. Troubleshoot to identify what is causing this and potential solutions.

### PR DESCRIPTION
**Pull request by kaitejohnson**
## Description

This PR closes #75. 

- `get_delay_estimate()` produces a warning if the first element of the delay_pmf is estimated at 0.
- `apply_delay()` function errors if the first element of delay_pmf is 0 and the triangle being passed in is a reporting triangle (meaning it has only a single value that is not NA in the last row).
- added tests to make sure this functionality works as expected

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [X] I have tested my changes locally.
- [X] I have added or updated unit tests where necessary.
- [X] I have updated the documentation if required.
- [X] My code follows the established coding standards.
- [X] I have added a news item linked to this PR.
- [X] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

File: R/get_delay_estimate.R [hunk 1]
```diff
@@ -94,5 +94,17 @@ get_delay_estimate <- function(triangle,
   # delay distribution
   pmf <- colSums(expectation) / sum(expectation)
 
+  if (pmf[1] == 0) {
+    cli_warn(
+      message =
+        c(
+          "Value of delay PMF at delay = 0 is 0. This delay PMF will not be ",
```
Comment (seabbs) [inline R/get_delay_estimate.R:101]: I think here we may want to suggest some action a user should/can take? 

From a separation of concerns perspective do we need this warning here as having a zero is a totally valid delay and it only becomes a problem when it is used for nowcasting?

File: R/validate.R [hunk 2]
```diff
@@ -100,5 +100,20 @@
...
     )
   }
+
+  # Make sure that nowcasts can be generated iteratively, ensuring delay_pmf[1]
+  # !=0 while the triangle is a reporting triangle (NAs all in bottom right)
+  if (is.na(triangle[nrow(triangle), 2]) && delay_pmf[1] == 0) {
+    cli_abort(
+      message = c(
+        "Value of delay PMF at delay = 0 is 0, and the latest reference time ",
+        "in the reporting matrix only contains a value at delay = 0. There ",
```
Comment (seabbs) [inline R/validate.R:110]:
```suggestion
        "in the reporting matrix only contains a value at delay = 0. There is",
```

**Review by seabbs — APPROVED** [review]
This looks good. Due to wanting separation of concerns I think I would go with just erroring when the delay is applied vs doubling up but I don't feel strongly about this.

File: R/get_delay_estimate.R (hunk 1 above)
Comment (kaitejohnson) [reply R/get_delay_estimate.R:101]: Sure I guess its a bit overkill, can remove.

File: R/validate.R [hunk 3]
```diff
@@ -100,5 +100,20 @@
       )
     )
   }
+
+  # Make sure that nowcasts can be generated iteratively, ensuring delay_pmf[1]
+  # !=0 while the triangle is a reporting triangle (NAs all in bottom right)
+  if (is.na(triangle[nrow(triangle), 2]) && delay_pmf[1] == 0) {
```
Comment (seabbs) [inline R/validate.R:106]: do you want to slightly loosen this check to very nearly 0 or is this enough?

Comment (kaitejohnson) [reply R/validate.R:106]: Hmmm, I think if it is very nearly 0, that means there was at least a single observation with delay =0 and then I don't think you'd want to consider reindexing
